"""Self-contained TokenFlow browser UI."""

PAGE = r'''<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>TokenFlow · Local Agent Console</title>
<style>
:root{--bg:#08111f;--panel:#101d31;--panel2:#14243c;--line:#263a58;--text:#e8f0ff;--muted:#91a4c2;--blue:#6ea8ff;--cyan:#4de1d2;--green:#68e0a2;--orange:#ffc46b;--red:#ff7892;--shadow:0 24px 70px #0008}
*{box-sizing:border-box}body{margin:0;min-height:100vh;color:var(--text);font:14px/1.6 Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;background:radial-gradient(circle at 8% 0%,#17335c 0,#08111f 38%),var(--bg)}
.shell{width:min(1440px,calc(100% - 48px));margin:0 auto;padding:32px 0 56px}.topbar{display:flex;align-items:center;justify-content:space-between;margin-bottom:28px}.brand{display:flex;gap:14px;align-items:center}.logo{width:44px;height:44px;display:grid;place-items:center;border-radius:14px;color:#06111f;background:linear-gradient(135deg,var(--cyan),var(--blue));font-weight:900;font-size:20px;box-shadow:0 0 32px #4de1d244}.eyebrow{text-transform:uppercase;letter-spacing:.16em;color:var(--cyan);font-size:11px;font-weight:800}.brand h1{margin:2px 0 0;font-size:25px;letter-spacing:-.03em}.top-actions{display:flex;align-items:center;gap:10px}.pill{display:inline-flex;align-items:center;gap:7px;border:1px solid var(--line);border-radius:999px;padding:7px 12px;color:var(--muted);background:#0d1a2c}.dot{width:8px;height:8px;border-radius:50%;background:var(--orange);box-shadow:0 0 12px currentColor}.dot.ok{background:var(--green)}
.hero{display:flex;align-items:end;justify-content:space-between;gap:24px;margin-bottom:22px}.hero h2{font-size:clamp(28px,4vw,48px);line-height:1.08;letter-spacing:-.05em;margin:0 0 10px;max-width:760px}.hero p{margin:0;color:var(--muted);max-width:720px;font-size:15px}.hero-note{padding:13px 15px;max-width:300px;border:1px solid #2f4c75;border-radius:14px;background:#102542;color:#b7c9e5}
.status-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:18px}.status-card,.panel{border:1px solid var(--line);background:linear-gradient(145deg,#12233b,#0d192b);box-shadow:var(--shadow);border-radius:18px}.status-card{padding:16px}.status-card .label{color:var(--muted);font-size:12px}.status-card strong{display:block;margin-top:6px;font-size:17px}.status-card small{display:block;color:var(--muted);margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.workspace{display:grid;grid-template-columns:minmax(0,1.02fr) minmax(0,.98fr);gap:18px}.panel{padding:22px}.panel-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:18px}.panel h3{margin:0;font-size:18px}.panel-sub{color:var(--muted);font-size:12px}.field{margin:15px 0}.field label{display:flex;justify-content:space-between;margin-bottom:7px;color:#cbd8ed;font-weight:700;font-size:12px}.field label span{color:var(--muted);font-weight:400}.input,.select,.textarea{width:100%;border:1px solid var(--line);border-radius:11px;background:#091525;color:var(--text);padding:11px 12px;outline:none;transition:.2s}.input:focus,.select:focus,.textarea:focus{border-color:var(--blue);box-shadow:0 0 0 3px #6ea8ff22}.textarea{min-height:254px;resize:vertical}.select{appearance:auto}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.file-row{display:flex;align-items:center;gap:10px}.file-row input{min-width:0;flex:1;color:var(--muted);font-size:12px}.hint{color:var(--muted);font-size:12px;margin-top:7px}.actions{display:flex;flex-wrap:wrap;gap:9px;margin-top:20px}.btn{border:1px solid var(--line);border-radius:10px;padding:10px 13px;background:#152945;color:#dce9ff;cursor:pointer;font-weight:700;transition:.18s}.btn:hover{transform:translateY(-1px);border-color:#6ea8ff99;background:#1c3961}.btn.primary{border-color:transparent;color:#06111f;background:linear-gradient(135deg,var(--cyan),var(--blue))}.btn.safe{color:#9ff0c8;border-color:#2f8062;background:#12362f}.btn:disabled{cursor:wait;opacity:.65;transform:none}.result{min-height:420px;margin:0;border:1px solid #263a58;border-radius:14px;padding:16px;white-space:pre-wrap;overflow:auto;background:#07101c;color:#cfe0fa;font:12px/1.65 "Cascadia Code",Consolas,monospace}.result.ok{border-color:#2f8062}.result.error{border-color:#a14459;color:#ffc2cc}.footer{display:flex;justify-content:space-between;gap:14px;margin-top:16px;color:var(--muted);font-size:12px}.link{color:var(--blue);cursor:pointer}.toast{position:fixed;right:24px;bottom:24px;max-width:360px;padding:12px 15px;border:1px solid var(--line);border-radius:12px;background:#12243d;box-shadow:var(--shadow);opacity:0;transform:translateY(10px);pointer-events:none;transition:.2s}.toast.show{opacity:1;transform:none}.hidden{display:none}@media(max-width:900px){.workspace{grid-template-columns:1fr}.status-grid{grid-template-columns:repeat(2,1fr)}.hero{display:block}.hero-note{margin-top:16px;max-width:none}}@media(max-width:560px){.shell{width:min(100% - 24px,1440px);padding-top:18px}.topbar{align-items:flex-start}.top-actions{display:none}.status-grid{grid-template-columns:1fr 1fr}.row{grid-template-columns:1fr}.panel{padding:16px}.actions .btn{flex:1 1 45%}}
@media(max-width:560px){.top-actions{display:flex;flex-wrap:wrap;justify-content:flex-end}.top-actions .pill:nth-child(2){display:none}.top-actions .btn{padding:8px 10px;font-size:12px}}
</style>
</head>
<body>
<div class="shell">
  <header class="topbar"><div class="brand"><div class="logo">TF</div><div><div class="eyebrow">Local Agent Runtime</div><h1>TokenFlow</h1></div></div><div class="top-actions"><span class="pill"><i id="healthDot" class="dot"></i><span id="healthText">检测中</span></span><span class="pill">127.0.0.1 · local only</span><button class="btn" onclick="shutdownRuntime()">关闭服务</button></div></header>
  <section class="hero"><div><h2>把上下文变轻，<br><span style="color:var(--cyan)">让执行更快。</span></h2><p>统一连接本地模型、云端兼容端点与 Agent Harness。先压缩、计数、检索，再把任务交给合适的执行器。</p></div><div class="hero-note">安全默认：本地绑定、Harness 只读/计划模式、PC Agent dry-run。</div></section>
  <section class="status-grid"><div class="status-card"><div class="label">TOKENIZER</div><strong id="tokenizerStatus">检测中</strong><small id="tokenizerMeta">—</small></div><div class="status-card"><div class="label">FREETOKEN</div><strong id="ftStatus">检测中</strong><small id="ftMeta">—</small></div><div class="status-card"><div class="label">HARNESS</div><strong id="harnessStatus">检测中</strong><small id="harnessMeta">—</small></div><div class="status-card"><div class="label">CACHE</div><strong id="storeStatus">检测中</strong><small id="storeMeta">—</small><button id="importStoreButton" class="btn hidden" style="margin-top:10px" onclick="importLegacyStore()">导入旧缓存</button></div></section>
  <section class="workspace"><div class="panel"><div class="panel-head"><div><h3>任务工作台</h3><div class="panel-sub">输入一次，选择执行策略</div></div><span class="pill">V5 MVP</span></div>
    <div class="field"><label for="task">任务 <span>Task</span></label><input class="input" id="task" value="总结下面的文档并提取关键结论"></div>
    <div class="field"><label for="content">内容 <span id="charCount">0 字符</span></label><textarea class="textarea" id="content" placeholder="粘贴文档、代码或表格内容"></textarea><div class="hint">支持直接粘贴，也可以上传 TXT / DOCX / XLSX / PDF。</div></div>
    <div class="file-row"><input id="file" type="file" accept=".txt,.md,.py,.json,.csv,.tsv,.docx,.xlsx,.pdf"><button class="btn" onclick="parseFile()">解析文件</button></div>
    <div class="row"><div class="field"><label for="provider">模型提供商</label><select class="select" id="provider"><option value="auto">自动路由（仅本机）</option><option value="freetoken">FreeToken（显式选择）</option><option value="ollama">Ollama（显式选择）</option><option value="laya">Laya 兼容端点（可能外发）</option><option value="cloud">云端兼容端点（会外发）</option></select></div><div class="field"><label for="model">模型</label><input class="input" id="model" value="auto" placeholder="auto 或模型名"></div></div>
    <div class="row"><div class="field"><label for="harness">Harness</label><select class="select" id="harness"><option value="auto">自动选择</option><option value="codex">Codex</option><option value="claude">Claude</option><option value="dsh">DSH</option></select></div><div class="field"><label>PC Agent</label><button class="btn safe" style="width:100%;margin:0" onclick="showPcPlan()">生成安全动作计划</button></div></div>
    <div class="field"><label for="pcActions">PC Agent 动作 JSON <span>仅生成 dry-run 计划</span></label><textarea class="textarea" id="pcActions" style="min-height:110px" spellcheck="false">[{"type":"key","key":"enter"}]</textarea><div class="hint">编辑动作数组后生成计划；不会在此页面执行鼠标或键盘操作。</div></div>
    <div class="actions"><button class="btn" onclick="runLocal()">本地预处理</button><button class="btn primary" onclick="unifiedModel()">统一模型路由</button><button class="btn" onclick="localModel()">FreeToken</button><button class="btn" onclick="execute()">交给 Harness</button></div>
    <div class="actions"><button class="btn safe" onclick="startFreeToken()">启动 FreeToken</button><button class="btn" onclick="installFreeToken()">安装 FreeToken</button></div>
  </div><div class="panel"><div class="panel-head"><div><h3>运行结果</h3><div class="panel-sub" id="resultMeta">等待执行</div></div><span class="link" onclick="clearResult()">清空</span></div><pre id="result" class="result">准备就绪。

TokenFlow 会先完成本地压缩和 Token 计数，再按你的选择调用模型或 Harness。</pre><div class="footer"><span id="statusLine">正在加载运行时状态…</span><span>Local-first · Explicit actions</span></div></div></section>
  <div id="toast" class="toast"></div>
</div>
<script>
const $=id=>document.getElementById(id), SESSION_TOKEN='__TOKENFLOW_SESSION_TOKEN__', result=$('result');let legacyImportedThisSession=false;
function show(value,meta=''){result.textContent=typeof value==='string'?value:JSON.stringify(value,null,2);$('resultMeta').textContent=meta||'已完成';result.className='result ok'}
function fail(value){result.textContent=typeof value==='string'?value:JSON.stringify(value,null,2);$('resultMeta').textContent='请求失败';result.className='result error'}
function toast(text){const node=$('toast');node.textContent=text;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),2600)}
function payload(){return {task:$('task').value,content:$('content').value,provider:$('provider').value,harness:$('harness').value,model:$('model').value||'auto'}}
async function post(path,body=payload()){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-TokenFlow-Token':SESSION_TOKEN},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw data;return data}
async function runLocal(){try{show('本地预处理中…','处理中');show(await post('/api/run'),'本地预处理完成')}catch(e){fail(e)}}
async function localModel(){try{show('正在调用 FreeToken…','请求中');show(await post('/api/local-chat'),'FreeToken 完成')}catch(e){fail(e)}}
async function unifiedModel(){if($('provider').value!=='auto'&&!confirm('任务和内容将发送到所选提供商的配置地址；该地址可能位于本机之外。确定继续吗？'))return;try{show('正在按提供商路由模型…','路由中');show(await post('/api/chat'),'统一模型路由完成')}catch(e){fail(e)}}
async function execute(){try{show('正在交给 Harness…','执行中');show(await post('/api/execute'),'Harness 执行完成')}catch(e){fail(e)}}
async function installFreeToken(){try{show(await post('/api/freetoken/install',{}),'安装器已打开');toast('请在安装器窗口中确认')}catch(e){fail(e)}}
async function startFreeToken(){try{show(await post('/api/freetoken/start',{}),'FreeToken 启动请求已发送');toast('正在启动本地模型服务');setTimeout(loadStatus,1600)}catch(e){fail(e)}}
async function shutdownRuntime(){if(!confirm('确定关闭 TokenFlow 本地服务？'))return;try{await post('/api/shutdown',{});$('healthDot').className='dot';$('healthText').textContent='已关闭';$('statusLine').textContent='TokenFlow 服务已关闭';toast('服务已关闭，可以关闭此页面')}catch(e){fail(e)}}
async function importLegacyStore(){if(!confirm('导入旧版缓存？现有缓存会按内容去重，旧数据库文件保留不变。'))return;try{const data=await post('/api/store/migrate',{});legacyImportedThisSession=true;show(data,'旧缓存导入完成');toast('旧数据库保持不变');await loadStatus()}catch(e){fail(e)}}
async function parseFile(){const file=$('file').files[0];if(!file){toast('请先选择文件');return}try{const body=new FormData();body.append('file',file);const response=await fetch('/api/parse',{method:'POST',headers:{'X-TokenFlow-Token':SESSION_TOKEN},body});const data=await response.json();if(!response.ok)throw data;$('content').value=data.text;updateCount();show({name:data.name,extension:data.extension,characters:data.characters},'文件解析完成');toast('文件内容已载入')}catch(e){fail(e)}}
async function showPcPlan(){try{const actions=JSON.parse($('pcActions').value);const data=await post('/api/pc/plan',{actions});show(data,'PC Agent 安全动作计划（dry-run）')}catch(e){fail(e)}}
function clearResult(){show('准备就绪。\n\nTokenFlow 会先完成本地压缩和 Token 计数，再按你的选择调用模型或 Harness。','等待执行')}
function updateCount(){$('charCount').textContent=$('content').value.length+' 字符'}
async function loadStatus(){try{const [tokenizer,ft,harness,store]=await Promise.all([fetch('/api/tokenizer').then(r=>r.json()),fetch('/api/freetoken').then(r=>r.json()),fetch('/api/harnesses').then(r=>r.json()),fetch('/api/store').then(r=>r.json())]);$('tokenizerStatus').textContent=tokenizer.exact?'Exact tokenizer':'Heuristic';$('tokenizerMeta').textContent=tokenizer.backend;$('ftStatus').textContent=ft.running?'运行中':(ft.installed?'已安装':'未安装');$('ftMeta').textContent=ft.version||'API 未连接';const installed=Object.values(harness).filter(x=>x.installed).length;$('harnessStatus').textContent=installed+' 个可用';$('harnessMeta').textContent=Object.keys(harness).join(' · ');$('storeStatus').textContent=store.documents+' 个文档';$('storeMeta').textContent=legacyImportedThisSession?'旧缓存已导入，源文件保留':(store.legacy_database_available?'发现旧版缓存，可导入':store.chunks+' 个分块');$('importStoreButton').classList.toggle('hidden',!store.legacy_database_available||legacyImportedThisSession);$('healthDot').className='dot ok';$('healthText').textContent='Runtime ready';$('statusLine').textContent='运行时状态已更新'}catch(e){$('healthText').textContent='部分服务不可用';$('statusLine').textContent='状态检测失败'}}
$('content').addEventListener('input',updateCount);updateCount();loadStatus();
</script>
</body>
</html>'''
